### ISSUE TITLE
The woorkboekdefinitie doesn't seems to work

### ISSUE THREAD

**Issue by danieltomasz** [oasido/Nederlands-Leren-Anki-Assistent#1]
A really nice helper-plugin!
I continually getting "Er zijn geen uitgebreide woordinformatie." when I try to search a woordboekdefinitie, forvo search is working really good.

**Comment by oasido** [comment]
![image](https://github.com/oasido/Nederlands-Leren-Anki-Assistent/assets/8614095/93b088f6-fb9e-4073-b536-a1cc6bffdaa6)
Thank you for reporting & sorry for the delay.
You can update the addon:
`2100409589`
https://ankiweb.net/shared/info/2100409589
https://github.com/oasido/Nederlands-Leren-Anki-Assistent/commit/0f876ab8fd45d276d9f13157da34664e770bf9d7
